jewel_mods = []
jewel_mods.append([r"([0-9]+)\(36-40\) to maximum Life", 35])
jewel_mods.append([r"([0-9]+)\(36-40\) to maximum Energy Shield", 35])
jewel_mods.append([r"([0-9]+)\(9-12\)% to Global Critical Strike Multiplier", 11])
jewel_mods.append([r"([0-9]+)\(6-8\)% increased Attack Speed if you've", 7])
jewel_mods.append([r"([0-9]+)\(5-7\)% increased Cast Speed if you've", 6])
jewel_mods.append([r"([0-9]+)\(2-4\)% of Physical Damage as Extra Fire Damage", 4])
jewel_mods.append([r"([0-9]+)\(5-7\)% increased maximum Life", 5])
jewel_mods.append([r"([0-9]+)\(6-8\)% increased maximum Energy Shield", 7])
jewel_mods.append([r"([0-9]+)\(12-15\)% to Critical Strike Multiplier", 12])
jewel_mods.append([r"([0-9]+)\(15-18\)% to Critical Strike Multiplier", 15])
jewel_mods.append([r"([0-9]+)\(4-6\)% increased Rarity of Items found", 6])
jewel_mods.append([r"([0-9]+)\(4-6\)% increased Rarity of Items found", 6])
jewel_mods.append([r"([0-9]+)\(7-13\)% to Chaos Resistance", 12])
jewel_mods.append([r"([0-9]+)\(6-8\)% to Fire Damage over Time Multiplier", 6])
jewel_mods.append([r"([0-9]+)\(6-8\)% to Chaos Damage over Time Multiplier", 6])
jewel_mods.append([r"([0-9]+)\(5-7\)% to Damage over Time Multiplier", 6])
