jewel_mods = []
jewel_mods.append([r"([0-9]+)\(31-35\) to maximum Life", 32, 1])
jewel_mods.append([r"([0-9]+)\(36-40\) to maximum Life", 32, 1])
jewel_mods.append([r"([0-9]+)\(36-40\) to maximum Energy Shield", 35, 1])
jewel_mods.append([r"([0-9]+)\(9-12\)% to Global Critical Strike Multiplier", 11, 1])
jewel_mods.append([r"([0-9]+)\(6-8\)% increased Attack Speed if you've", 7, 1])
jewel_mods.append([r"([0-9]+)\(5-7\)% increased Cast Speed if you've", 6, 1])
jewel_mods.append([r"([0-9]+)\(2-4\)% of Physical Damage as Extra Fire Damage", 4, 1])
jewel_mods.append([r"([0-9]+)\(5-7\)% increased maximum Life", 5, 1.5])
jewel_mods.append([r"([0-9]+)\(6-8\)% increased maximum Energy Shield", 7, 1])
jewel_mods.append([r"([0-9]+)\(12-15\)% to Critical Strike Multiplier", 12, 1])
jewel_mods.append([r"([0-9]+)\(15-18\)% to Critical Strike Multiplier", 15, 1])
jewel_mods.append(
    [r"([0-9]+)\(15-18\)% to Critical Strike Multiplier with Fire", 15, -1]
)
jewel_mods.append([r"([0-9]+)\(4-6\)% increased Rarity of Items found", 6, 1.4])
jewel_mods.append([r"([0-9]+)\(7-13\)% to Chaos Resistance", 11, 1])
jewel_mods.append([r"([0-9]+)\(6-8\)% to Fire Damage over Time Multiplier", 6, 0.6])
jewel_mods.append([r"([0-9]+)\(6-8\)% to Chaos Damage over Time Multiplier", 6, 0.6])
jewel_mods.append([r"([0-9]+)\(4-6\)% to Damage over Time Multiplier", 6, 0.6])
jewel_mods.append([r"([0-9]+)\(2-3\)% increased Mana Reservation", 3, 1])
jewel_mods.append([r"([0-9]+)\(6-10\)% increased Flask Effect Duration", 8, 1])
